### ISSUE TITLE
Running Path Schema - difference between id and uuid

### ISSUE THREAD

**Issue by apriljunge** [railtoolkit/schema#5]
Why are there two id properties (`id` and `uuid`)?

**Comment by kaat0** [comment]
The `uuid` field makes identifying `paths` or `trains` across projects possible. The `id` field can be used for human-readable identification.

For example, vehicles might have different designations depending on the company. See [Siemens EuroSprinter](https://de.wikipedia.org/wiki/Siemens_EuroSprinter).

Renaming the `id` field to something more unambiguous might make sense.

**Comment by kaat0** [comment]
As mentioned in [TrainRuns.jl/issues/48](https://github.com/railtoolkit/TrainRuns.jl/issues/48#issuecomment-2010778807), the `name` can be renamed into `description`.
