### ISSUE TITLE
Clearify "station in meter"?

### ISSUE THREAD

**Issue by apriljunge** [railtoolkit/schema#6]
It's not clear to me what _station in meter_ means.
Could it also be translated as position in meters?

**Comment by kaat0** [comment]
Sequential position in meters

**Comment by apriljunge** [comment]
I think changing that in the docs would clearify that?
Do you agree?

**Comment by kaat0** [comment]
If it only needs to be clarified in the docs depends on the result of the discussion in #4. Otherwise, I agree.

**Comment by kaat0** [comment]
addressed in #19
